-- ============================================================
-- Quiz App Database Schema
-- ============================================================

USE railway;

-- ------------------------------------------------------------
-- USERS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
    profile_image VARCHAR(255) DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_users_email (email),
    INDEX idx_users_username (username)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- CATEGORIES
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- QUESTIONS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_id INT NOT NULL,
    question TEXT NOT NULL,
    option_a VARCHAR(500) NOT NULL,
    option_b VARCHAR(500) NOT NULL,
    option_c VARCHAR(500) NOT NULL,
    option_d VARCHAR(500) NOT NULL,
    correct_answer ENUM('A', 'B', 'C', 'D') NOT NULL,
    explanation TEXT DEFAULT NULL,
    difficulty ENUM('easy', 'medium', 'hard') NOT NULL DEFAULT 'medium',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    INDEX idx_questions_category (category_id),
    INDEX idx_questions_difficulty (difficulty)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- QUIZ RESULTS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quiz_results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    category_id INT NOT NULL,
    difficulty ENUM('easy', 'medium', 'hard', 'mixed') NOT NULL DEFAULT 'mixed',
    total_questions INT NOT NULL,
    correct_answers INT NOT NULL DEFAULT 0,
    wrong_answers INT NOT NULL DEFAULT 0,
    score INT NOT NULL DEFAULT 0,
    percentage DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    time_taken INT NOT NULL DEFAULT 0 COMMENT 'seconds',
    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    INDEX idx_results_user (user_id),
    INDEX idx_results_category (category_id)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- QUIZ ANSWERS (answer history)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quiz_answers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    quiz_result_id INT NOT NULL,
    question_id INT NOT NULL,
    selected_answer ENUM('A', 'B', 'C', 'D', 'NONE') NOT NULL DEFAULT 'NONE',
    correct_answer ENUM('A', 'B', 'C', 'D') NOT NULL,
    is_correct TINYINT(1) NOT NULL DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (quiz_result_id) REFERENCES quiz_results(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
    INDEX idx_answers_result (quiz_result_id)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- SEED DATA: categories
-- ------------------------------------------------------------
INSERT IGNORE INTO categories (name, description) VALUES
('HTML', 'Questions about HTML markup and structure'),
('CSS', 'Questions about styling and layout'),
('JavaScript', 'Questions about JS fundamentals'),
('C Programming', 'Questions about the C language'),
('Database', 'Questions about SQL and databases'),
('General Knowledge', 'Miscellaneous general knowledge questions');

-- ------------------------------------------------------------
-- SEED DATA: sample questions (category_id references insert order 1-6 above)
-- ------------------------------------------------------------
INSERT INTO questions (category_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty) VALUES
(1, 'What does HTML stand for?', 'Hyper Trainer Marking Language', 'Hyper Text Markup Language', 'Hyper Text Marketing Language', 'Hyper Text Markup Leveler', 'B', 'HTML stands for Hyper Text Markup Language.', 'easy'),
(1, 'Which tag is used to create a hyperlink?', '<link>', '<a>', '<href>', '<url>', 'B', 'The <a> tag defines a hyperlink using the href attribute.', 'easy'),
(2, 'Which property changes text color in CSS?', 'font-color', 'text-color', 'color', 'foreground-color', 'C', 'The color property sets the text color.', 'easy'),
(2, 'Which CSS property controls spacing outside an element?', 'padding', 'margin', 'spacing', 'border', 'B', 'The margin property controls space outside an element border.', 'medium'),
(3, 'Which keyword declares a block-scoped variable in JS?', 'var', 'let', 'global', 'static', 'B', 'let declares a block-scoped variable, unlike var.', 'easy'),
(3, 'What does strict equality (===) check in JavaScript?', 'Value only', 'Type only', 'Value and type', 'Neither', 'C', 'Strict equality checks both value and type.', 'medium'),
(4, 'Which function is used to allocate memory dynamically in C?', 'alloc()', 'malloc()', 'new()', 'create()', 'B', 'malloc() dynamically allocates memory on the heap.', 'medium'),
(5, 'Which SQL statement is used to extract data from a database?', 'GET', 'EXTRACT', 'SELECT', 'OPEN', 'C', 'SELECT is used to query data from a database.', 'easy'),
(6, 'What is the capital of France?', 'Berlin', 'Madrid', 'Paris', 'Rome', 'C', 'Paris is the capital of France.', 'easy');

-- ------------------------------------------------------------
-- Note: create the first admin manually after registering, e.g.:
-- UPDATE users SET role = 'admin' WHERE email = 'you@example.com';
-- ------------------------------------------------------------
USE railway;
INSERT INTO questions
(category_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty)
VALUES
('1','What does HTML stand for?','HyperText Markup Language','Hyper Trainer Marking Language','HighText Machine Language','Hyperlink Text Management Language','A','The correct answer is A. This is a fundamental HTML concept.','easy'),
('1','Which element creates the largest heading?','<h6>','<heading>','<h1>','<head>','C','The correct answer is C. This is a fundamental HTML concept.','easy'),
('1','Which element creates a hyperlink?','<link>','<a>','<href>','<url>','B','The correct answer is B. This is a fundamental HTML concept.','easy'),
('1','Which attribute specifies an image source?','href','src','link','source','B','The correct answer is B. This is a fundamental HTML concept.','easy'),
('1','Which element inserts an image?','<picture>','<img>','<image>','<src>','B','The correct answer is B. This is a fundamental HTML concept.','easy'),
('1','Which element creates an unordered list?','<ol>','<list>','<ul>','<li>','C','The correct answer is C. This is a fundamental HTML concept.','easy'),
('1','Which element creates an ordered list?','<ul>','<ol>','<li>','<order>','B','The correct answer is B. This is a fundamental HTML concept.','easy'),
('1','Which element represents a list item?','<item>','<li>','<list>','<ul>','B','The correct answer is B. This is a fundamental HTML concept.','easy'),
('1','Which element creates a paragraph?','<p>','<para>','<text>','<paragraph>','A','The correct answer is A. This is a fundamental HTML concept.','easy'),
('1','Which element inserts a line break?','<break>','<lb>','<br>','<newline>','C','The correct answer is C. This is a fundamental HTML concept.','easy'),
('1','Which element contains document metadata?','<body>','<meta>','<head>','<info>','C','The correct answer is C. This is a fundamental HTML concept.','easy'),
('1','Which element contains visible page content?','<head>','<body>','<mainhead>','<content>','B','The correct answer is B. This is a fundamental HTML concept.','easy'),
('1','Which declaration defines an HTML5 document?','<!DOCTYPE html>','<doctype html5>','<!HTML5>','<html5>','A','The correct answer is A. This is a fundamental HTML concept.','easy'),
('1','Which attribute provides alternative text for an image?','title','alt','text','description','B','The correct answer is B. This is a fundamental HTML concept.','easy'),
('1','Which element defines a table row?','<td>','<tr>','<row>','<th>','B','The correct answer is B. This is a fundamental HTML concept.','easy'),
('1','Which element defines a table data cell?','<td>','<cell>','<data>','<tr>','A','The correct answer is A. This is a fundamental HTML concept.','easy'),
('1','Which element defines a table header cell?','<thead>','<header>','<th>','<td>','C','The correct answer is C. This is a fundamental HTML concept.','easy'),
('1','Which element groups table header content?','<thead>','<top>','<thgroup>','<header>','A','The correct answer is A. This is a fundamental HTML concept.','easy'),
('1','Which element defines a table body?','<tbody>','<bodytable>','<tablebody>','<body>','A','The correct answer is A. This is a fundamental HTML concept.','easy'),
('1','Which element creates a form?','<input>','<form>','<fieldset>','<submit>','B','The correct answer is B. This is a fundamental HTML concept.','easy'),
('1','Which input type hides typed characters?','text','hidden','password','secret','C','The correct answer is C. This is a fundamental HTML concept.','medium'),
('1','Which attribute makes an input mandatory?','required','must','validate','needed','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element creates a dropdown list?','<select>','<dropdown>','<option>','<listbox>','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element defines an option in a dropdown?','<choice>','<select>','<option>','<item>','C','The correct answer is C. This is a fundamental HTML concept.','medium'),
('1','Which element creates a multi-line text field?','<input>','<textarea>','<text>','<multiline>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which attribute gives an element a unique identifier?','class','id','name','key','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which attribute assigns reusable classes?','class','style','group','type','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element is semantically used for navigation?','<navigate>','<nav>','<navigation>','<links>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which element represents the main content?','<main>','<content>','<primary>','<section-main>','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element represents an independent article?','<article>','<post>','<story>','<content>','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element represents a thematic section?','<section>','<part>','<area>','<theme>','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element is used for footer content?','<bottom>','<footer>','<foot>','<end>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which element is commonly used for introductory content?','<header>','<intro>','<top>','<banner>','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element embeds video?','<movie>','<video>','<media>','<player>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which element embeds audio?','<sound>','<audio>','<music>','<media-audio>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which element draws graphics with scripts?','<draw>','<canvas>','<graphics>','<paint>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which element embeds another webpage?','<frame>','<iframe>','<embedpage>','<window>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which target value opens a link in a new browsing context?','target="_blank"','new="true"','open="new"','window="blank"','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element provides a caption for a figure?','<caption>','<figcaption>','<figurecaption>','<label>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which element wraps a self-contained figure?','<figure>','<imagebox>','<fig>','<media>','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element emphasizes text semantically?','<em>','<italic>','<i-em>','<strong>','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element indicates strong importance?','<bold>','<strong>','<important>','<bstrong>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which element creates a thematic horizontal break?','<line>','<hr>','<breakline>','<horizontal>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which element marks a short quotation?','<quote>','<q>','<quotation>','<citequote>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which element marks a long quotation block?','<blockquote>','<quote-block>','<longquote>','<bq>','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element represents a date or time?','<date>','<time>','<datetime>','<calendar>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which element labels a form control?','<label>','<caption>','<formlabel>','<name>','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element groups related form controls?','<group>','<fieldset>','<formgroup>','<controls>','B','The correct answer is B. This is a fundamental HTML concept.','medium'),
('1','Which element gives a fieldset a caption?','<legend>','<caption>','<title>','<fieldset-title>','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('1','Which element defines the browser-tab title?','<title>','<tab>','<headtitle>','<name>','A','The correct answer is A. This is a fundamental HTML concept.','medium'),
('2','What does CSS stand for?','Cascading Style Sheets','Computer Style Syntax','Creative Styling System','Coded Style Sheets','A','The correct answer is A. This is a fundamental CSS concept.','easy'),
('2','Which property changes text color?','font-color','text-color','color','foreground','C','The correct answer is C. This is a fundamental CSS concept.','easy'),
('2','Which property changes background color?','bgcolor','background-color','color-background','back-color','B','The correct answer is B. This is a fundamental CSS concept.','easy'),
('2','Which property changes font size?','text-size','font-size','size','font-scale','B','The correct answer is B. This is a fundamental CSS concept.','easy'),
('2','Which property changes the typeface?','font-family','font-type','typeface','text-family','A','The correct answer is A. This is a fundamental CSS concept.','easy'),
('2','Which property makes text bold?','font-weight','text-bold','font-style','weight-text','A','The correct answer is A. This is a fundamental CSS concept.','easy'),
('2','Which property aligns text horizontally?','text-align','align-text','horizontal-align','text-position','A','The correct answer is A. This is a fundamental CSS concept.','easy'),
('2','Which property controls outside spacing?','padding','margin','spacing','outside','B','The correct answer is B. This is a fundamental CSS concept.','easy'),
('2','Which property controls inside spacing?','margin','padding','inner-space','border-space','B','The correct answer is B. This is a fundamental CSS concept.','easy'),
('2','Which property creates a border?','outline-box','border','frame','edge','B','The correct answer is B. This is a fundamental CSS concept.','easy'),
('2','Which property rounds corners?','corner-radius','border-radius','radius','round-corner','B','The correct answer is B. This is a fundamental CSS concept.','easy'),
('2','Which declaration enables Flexbox?','display:flex','position:flex','layout:flex','flex:display','A','The correct answer is A. This is a fundamental CSS concept.','easy'),
('2','Which declaration enables CSS Grid?','display:grid','grid:display','layout:grid','position:grid','A','The correct answer is A. This is a fundamental CSS concept.','easy'),
('2','Which property controls width?','size','width','element-width','x-size','B','The correct answer is B. This is a fundamental CSS concept.','easy'),
('2','Which property controls height?','height','length','y-size','element-height','A','The correct answer is A. This is a fundamental CSS concept.','easy'),
('2','Which property sets maximum width?','width-max','max-width','maximum-width','limit-width','B','The correct answer is B. This is a fundamental CSS concept.','easy'),
('2','Which property controls transparency?','opacity','transparent','alpha','visibility','A','The correct answer is A. This is a fundamental CSS concept.','easy'),
('2','Which property controls element visibility?','display','visibility','visible','show','B','The correct answer is B. This is a fundamental CSS concept.','easy'),
('2','Which property controls stacking order?','layer','z-index','stack','index-layer','B','The correct answer is B. This is a fundamental CSS concept.','easy'),
('2','Which position value is the normal positioning mode?','absolute','fixed','static','floating','C','The correct answer is C. This is a fundamental CSS concept.','easy'),
('2','Which position value removes an element from normal flow?','absolute','static','relative','normal','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property floats an element?','float','side','position-side','flow','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property controls overflow?','overflow','over-content','clip','content-flow','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property sets a background image?','background-image','image-background','bg-image-url','background-src','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property controls background repetition?','background-repeat','repeat-background','image-repeat','bg-loop','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property controls background image size?','background-size','image-size','bg-scale','background-scale','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property sets space between flex/grid items?','gap','space','item-gap-only','distance','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which flex property controls main-axis alignment?','align-items','justify-content','flex-align','main-align','B','The correct answer is B. This is a fundamental CSS concept.','medium'),
('2','Which flex property controls cross-axis alignment?','justify-content','align-items','cross-align','item-position','B','The correct answer is B. This is a fundamental CSS concept.','medium'),
('2','Which property sets flex direction?','flex-direction','direction-flex','flow-direction','flex-axis','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property allows flex wrapping?','flex-wrap','wrap-flex','item-wrap','flex-lines','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property changes flex item order?','item-order','order','flex-ordering','position-order','B','The correct answer is B. This is a fundamental CSS concept.','medium'),
('2','Which unit is relative to root font size?','em','rem','px','vh','B','The correct answer is B. This is a fundamental CSS concept.','medium'),
('2','Which unit is relative to viewport width?','vw','vh','vmin','w','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which unit is relative to viewport height?','vh','vw','vmax','h','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which pseudo-class applies on hover?','::hover',':hover','hover()','@hover','B','The correct answer is B. This is a fundamental CSS concept.','medium'),
('2','Which pseudo-class applies when focused?','::focus',':focus','focus()','@focus','B','The correct answer is B. This is a fundamental CSS concept.','medium'),
('2','Which pseudo-element inserts content before?','::before',':before-content','::pre','::start','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which pseudo-element inserts content after?','::after',':after-content','::post','::end','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property controls the mouse pointer?','mouse','cursor','pointer-style','hand','B','The correct answer is B. This is a fundamental CSS concept.','medium'),
('2','Which property can underline text?','text-line','text-decoration','underline','font-decoration','B','The correct answer is B. This is a fundamental CSS concept.','medium'),
('2','Which property controls line spacing?','line-height','text-height','line-space','leading','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property controls letter spacing?','letter-spacing','char-space','text-spacing','glyph-gap','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property controls word spacing?','word-spacing','text-word-gap','words-space','word-gap-size','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property can prevent text wrapping?','white-space','text-wrap:none','nowrap','wrap-control','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which at-rule is used for media queries?','@responsive','@media','@screen','@query','B','The correct answer is B. This is a fundamental CSS concept.','medium'),
('2','Which position value can stick during scrolling?','sticky','fixed-sticky','scroll-sticky','positioned','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which function can clamp a value between minimum and maximum?','minmax()','clamp()','responsive()','range()','B','The correct answer is B. This is a fundamental CSS concept.','medium'),
('2','Which property defines transition duration?','transition-duration','transition-time','duration','animation-duration','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('2','Which property defines an animation name?','animation-name','name-animation','keyframe-name','animate-name','A','The correct answer is A. This is a fundamental CSS concept.','medium'),
('3','Which keyword declares a reassignable block-scoped variable?','var','let','const','define','B','The correct answer is B. This is a fundamental JavaScript concept.','easy'),
('3','Which keyword declares a non-reassignable binding?','let','var','const','static','C','The correct answer is C. This is a fundamental JavaScript concept.','easy'),
('3','Which keyword declares a function-scoped variable?','var','let','const','scope','A','The correct answer is A. This is a fundamental JavaScript concept.','easy'),
('3','Which operator checks strict equality?','==','=','===','!==','C','The correct answer is C. This is a fundamental JavaScript concept.','easy'),
('3','Which operator checks strict inequality?','!=','!==','<>','not=','B','The correct answer is B. This is a fundamental JavaScript concept.','easy'),
('3','Which method prints to the console?','console.log()','print()','echo()','log.console()','A','The correct answer is A. This is a fundamental JavaScript concept.','easy'),
('3','Which method parses JSON text?','JSON.parse()','JSON.stringify()','JSON.object()','parse.JSON()','A','The correct answer is A. This is a fundamental JavaScript concept.','easy'),
('3','Which method converts a value to JSON text?','JSON.parse()','JSON.stringify()','JSON.toText()','string.JSON()','B','The correct answer is B. This is a fundamental JavaScript concept.','easy'),
('3','Which array method adds to the end?','push()','pop()','shift()','addEnd()','A','The correct answer is A. This is a fundamental JavaScript concept.','easy'),
('3','Which array method removes the last item?','push()','pop()','removeLast()','delete()','B','The correct answer is B. This is a fundamental JavaScript concept.','easy'),
('3','Which array method removes the first item?','shift()','unshift()','popFirst()','removeFirst()','A','The correct answer is A. This is a fundamental JavaScript concept.','easy'),
('3','Which array method adds to the beginning?','push()','prepend()','unshift()','start()','C','The correct answer is C. This is a fundamental JavaScript concept.','easy'),
('3','Which array property gives the number of elements?','count','size','length','items','C','The correct answer is C. This is a fundamental JavaScript concept.','easy'),
('3','Which method transforms each array element into a new array?','map()','filter()','reduce()','forEach()','A','The correct answer is A. This is a fundamental JavaScript concept.','easy'),
('3','Which method keeps elements that pass a test?','map()','filter()','find()','test()','B','The correct answer is B. This is a fundamental JavaScript concept.','easy'),
('3','Which method reduces an array to one accumulated result?','reduce()','joinAll()','combine()','merge()','A','The correct answer is A. This is a fundamental JavaScript concept.','easy'),
('3','Which method runs a function for each element?','forEach()','eachNew()','loop()','iterate()','A','The correct answer is A. This is a fundamental JavaScript concept.','easy'),
('3','Which keyword exits a loop?','stop','break','exit','return-loop','B','The correct answer is B. This is a fundamental JavaScript concept.','easy'),
('3','Which keyword skips to the next iteration?','skip','continue','next','pass','B','The correct answer is B. This is a fundamental JavaScript concept.','easy'),
('3','Which keyword defines a function?','func','function','def','method','B','The correct answer is B. This is a fundamental JavaScript concept.','easy'),
('3','Which syntax is used for an arrow function?','=>','->','<=','::','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','What does DOM stand for?','Document Object Model','Data Object Model','Document Order Map','Digital Object Management','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which method selects an element by ID?','getElementById()','queryById()','selectId()','findId()','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which method selects the first CSS-selector match?','querySelector()','queryFirst()','selectOne()','cssSelect()','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which property sets HTML content?','innerHTML','htmlContent','contentHTML','domHTML','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which property sets text content?','textContent','innerTextOnly','textValue','contentTextOnly','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which method registers an event listener?','addEventListener()','onEvent()','listen()','eventAdd()','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which event commonly fires after a click?','press','click','tap','button','B','The correct answer is B. This is a fundamental JavaScript concept.','medium'),
('3','Which keyword defines a class?','class','object','type','struct','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which keyword refers to the current object context?','self','this','current','that','B','The correct answer is B. This is a fundamental JavaScript concept.','medium'),
('3','Which construct handles exceptions?','try...catch','if...error','error...catch','handle...exception','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which keyword throws an exception?','throw','error','raise','exception','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which method runs a function once after a delay?','setTimeout()','setDelay()','delayRun()','after()','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which method repeatedly runs a function at intervals?','setInterval()','repeatEvery()','loopTimer()','interval()','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which value represents intentional absence?','undefined','null','empty','false','B','The correct answer is B. This is a fundamental JavaScript concept.','medium'),
('3','Which value commonly means a variable is not assigned?','null','undefined','void-object','none','B','The correct answer is B. This is a fundamental JavaScript concept.','medium'),
('3','What does NaN mean?','Not a Number','Null as Number','No Assigned Name','Negative and Null','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which operator returns a value''s type?','typeof','type()','instance()','gettype','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which keyword waits for a Promise inside async code?','wait','await','pause','defer','B','The correct answer is B. This is a fundamental JavaScript concept.','medium'),
('3','Which keyword marks a function as asynchronous?','async','awaitable','promise','defer','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','What represents the eventual result of async work?','Promise','FutureOnly','AsyncObject','Result','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which Promise method handles fulfillment?','then()','done()','success()','resolve()','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which Promise method handles rejection?','catch()','error()','reject()','fail()','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which operator provides a fallback for null/undefined?','||','??','??=','?:','B','The correct answer is B. This is a fundamental JavaScript concept.','medium'),
('3','Which syntax is optional chaining?','?.','?.?','::','??','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which method converts text to lowercase?','toLowerCase()','lower()','lowerCaseText()','downcase()','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which method converts text to uppercase?','toUpperCase()','upper()','upperCaseText()','upcase()','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which method returns part of a string?','slice()','part()','substringOnly()','cut()','A','The correct answer is A. This is a fundamental JavaScript concept.','medium'),
('3','Which operator means logical AND?','&','&&','AND','||','B','The correct answer is B. This is a fundamental JavaScript concept.','medium'),
('3','Which operator means logical OR?','|','||','OR','&&','B','The correct answer is B. This is a fundamental JavaScript concept.','medium'),
('4','Which header declares printf() and scanf()?','<stdio.h>','<stdlib.h>','<string.h>','<math.h>','A','The correct answer is A. This is a fundamental C Programming concept.','easy'),
('4','What is the usual C program entry point?','start()','main()','begin()','run()','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which format specifier prints an int?','%f','%c','%d','%s','C','The correct answer is C. This is a fundamental C Programming concept.','easy'),
('4','Which format specifier prints a float?','%f','%d','%c','%i','A','The correct answer is A. This is a fundamental C Programming concept.','easy'),
('4','Which format specifier prints a character?','%s','%c','%ch','%char','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which format specifier prints a string?','%str','%s','%text','%c','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which symbol ends a C statement?',';',':','.',',','A','The correct answer is A. This is a fundamental C Programming concept.','easy'),
('4','Which operator assigns a value?','==','=','=>',':=','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which operator tests equality?','=','==','===','!=','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which operator means logical AND?','&','&&','and','||','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which operator means logical OR?','|','||','or','&&','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which keyword declares a constant?','constant','const','fixed','readonly','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which keyword returns a value?','send','return','back','output','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which loop is commonly used for a known iteration count?','for','if','switch','goto','A','The correct answer is A. This is a fundamental C Programming concept.','easy'),
('4','Which loop checks its condition before each iteration?','while','do...while','repeat','loop','A','The correct answer is A. This is a fundamental C Programming concept.','easy'),
('4','Which loop executes at least once?','while','for','do...while','foreach','C','The correct answer is C. This is a fundamental C Programming concept.','easy'),
('4','Which statement selects among cases?','switch','choose','select','caseonly','A','The correct answer is A. This is a fundamental C Programming concept.','easy'),
('4','Which keyword exits a loop or switch?','stop','break','exit','leave','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which keyword skips the current iteration?','skip','continue','next','pass','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which operator gets a variable''s address?','*','&','@','#','B','The correct answer is B. This is a fundamental C Programming concept.','easy'),
('4','Which operator dereferences a pointer?','&','*','->','%','B','The correct answer is B. This is a fundamental C Programming concept.','medium'),
('4','Which header declares malloc()?','<stdio.h>','<stdlib.h>','<memory.h>','<alloc.h>','B','The correct answer is B. This is a fundamental C Programming concept.','medium'),
('4','Which function allocates dynamic memory?','malloc()','allocmem()','new()','memory()','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which function frees dynamic memory?','delete()','free()','release()','remove()','B','The correct answer is B. This is a fundamental C Programming concept.','medium'),
('4','Which header declares strlen()?','<string.h>','<stdio.h>','<stdlib.h>','<ctype.h>','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which function returns C-string length?','strsize()','strlen()','length()','stringlen()','B','The correct answer is B. This is a fundamental C Programming concept.','medium'),
('4','Which function copies a C string?','strcopy()','strcpy()','copystr()','string_copy()','B','The correct answer is B. This is a fundamental C Programming concept.','medium'),
('4','Which function compares C strings?','strcmp()','strcompare()','compare()','cmpstr()','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','How does a C string terminate?','\\n','\\0','EOF','NULL','B','The correct answer is B. This is a fundamental C Programming concept.','medium'),
('4','Which type stores one character?','char','string','character','byte','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which type commonly stores whole numbers?','int','float','decimal','number','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which type stores single-precision floating point?','float','real','decimal','double-only','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which keyword defines a structure?','record','struct','structure','object','B','The correct answer is B. This is a fundamental C Programming concept.','medium'),
('4','Which keyword defines an enumeration?','enum','enumerate','list','choice','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which operator accesses a struct member through a pointer?','->','.','::','=>','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which operator accesses a normal struct member?','->','.','::','&','B','The correct answer is B. This is a fundamental C Programming concept.','medium'),
('4','Which directive includes a header?','#include','#header','#import','#using','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which directive defines a macro?','#macro','#define','#const','#set','B','The correct answer is B. This is a fundamental C Programming concept.','medium'),
('4','Which symbol starts a single-line comment?','//','<!--','##','**','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which symbols create a block comment?','/* */','// //','<!-- -->','## ##','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','What does sizeof return?','Size in bytes','Memory address','Variable value','Bit count only','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which function converts a string to an integer?','atoi()','strint()','toint()','parseInt()','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which function generates a pseudo-random integer?','random()','rand()','rnd()','randomInt()','B','The correct answer is B. This is a fundamental C Programming concept.','medium'),
('4','Which function terminates a C program?','stop()','exit()','quit()','end()','B','The correct answer is B. This is a fundamental C Programming concept.','medium'),
('4','Which header declares exit()?','<stdlib.h>','<stdio.h>','<process.h>','<system.h>','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','What is an array?','A collection of elements of the same declared type','A single character','A function pointer only','A file','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','What is the first index of a C array?','0','1','-1','Depends always','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which keyword specifies automatic storage duration?','auto','local','var','register-only','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which keyword can suggest register storage?','register','fast','cpu','cache','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('4','Which function reads formatted standard input?','scanf()','input()','read()','getsafe()','A','The correct answer is A. This is a fundamental C Programming concept.','medium'),
('5','What does SQL stand for?','Structured Query Language','Simple Query Language','System Query Logic','Structured Question Language','A','The correct answer is A. This is a fundamental Database concept.','easy'),
('5','Which statement retrieves data?','SELECT','GET','FETCHONLY','READ','A','The correct answer is A. This is a fundamental Database concept.','easy'),
('5','Which statement inserts rows?','ADD','INSERT','CREATE','APPENDSQL','B','The correct answer is B. This is a fundamental Database concept.','easy'),
('5','Which statement changes existing rows?','CHANGE','UPDATE','MODIFYTABLE','EDIT','B','The correct answer is B. This is a fundamental Database concept.','easy'),
('5','Which statement removes rows?','REMOVE','DELETE','DROP','CLEAR','B','The correct answer is B. This is a fundamental Database concept.','easy'),
('5','Which statement creates a table?','MAKE TABLE','CREATE TABLE','NEW TABLE','BUILD TABLE','B','The correct answer is B. This is a fundamental Database concept.','easy'),
('5','Which statement removes a table?','DELETE TABLE','DROP TABLE','REMOVE TABLE','CLEAR TABLE','B','The correct answer is B. This is a fundamental Database concept.','easy'),
('5','Which clause filters rows?','FILTER','WHERE','HAVINGONLY','CHECK','B','The correct answer is B. This is a fundamental Database concept.','easy'),
('5','Which clause sorts results?','SORT BY','ORDER BY','ARRANGE BY','GROUP BY','B','The correct answer is B. This is a fundamental Database concept.','easy'),
('5','Which clause groups rows?','GROUP BY','ORDER BY','COLLECT BY','COMBINE BY','A','The correct answer is A. This is a fundamental Database concept.','easy'),
('5','Which clause filters grouped results?','WHERE','HAVING','GROUP WHERE','AFTER GROUP','B','The correct answer is B. This is a fundamental Database concept.','easy'),
('5','Which function counts rows/values?','COUNT()','NUMBER()','TOTAL()','ROWS()','A','The correct answer is A. This is a fundamental Database concept.','easy'),
('5','Which function calculates an average?','AVG()','MEAN()','AVERAGE()','MID()','A','The correct answer is A. This is a fundamental Database concept.','easy'),
('5','Which function calculates a total?','SUM()','TOTAL()','ADD()','PLUS()','A','The correct answer is A. This is a fundamental Database concept.','easy'),
('5','Which function returns the largest value?','TOP()','MAX()','HIGH()','LARGEST()','B','The correct answer is B. This is a fundamental Database concept.','easy'),
('5','Which function returns the smallest value?','MIN()','LOW()','SMALLEST()','BOTTOM()','A','The correct answer is A. This is a fundamental Database concept.','easy'),
('5','What is a primary key?','A column or set of columns that uniquely identifies a row','A database password','Any indexed column','A foreign table','A','The correct answer is A. This is a fundamental Database concept.','easy'),
('5','What is a foreign key?','A column that references a key in another table','A backup key','A login key','A random identifier','A','The correct answer is A. This is a fundamental Database concept.','easy'),
('5','Which constraint prevents NULL values?','UNIQUE','NOT NULL','NO EMPTY','REQUIRED KEY','B','The correct answer is B. This is a fundamental Database concept.','easy'),
('5','Which constraint prevents duplicate values?','UNIQUE','DISTINCT','NO DUP','SINGLE','A','The correct answer is A. This is a fundamental Database concept.','easy'),
('5','Which constraint enforces a condition?','CHECK','RULE','VALIDATE','FILTER','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Which command creates a database?','CREATE DATABASE','NEW DATABASE','MAKE DATABASE','ADD DATABASE','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Which command changes table structure?','ALTER TABLE','UPDATE TABLE','CHANGE TABLE DATA','EDIT TABLE','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Which keyword removes duplicates from a SELECT result?','UNIQUE','DISTINCT','ONLY','DEDUP','B','The correct answer is B. This is a fundamental Database concept.','medium'),
('5','Which operator matches a text pattern?','LIKE','MATCHES','PATTERN','SEARCHLIKE','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Which LIKE wildcard matches any sequence?','_','%','*','?','B','The correct answer is B. This is a fundamental Database concept.','medium'),
('5','Which LIKE wildcard matches one character?','%','_','?','*','B','The correct answer is B. This is a fundamental Database concept.','medium'),
('5','Which operator checks a range?','BETWEEN','RANGE','INRANGE','WITHIN','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Which operator checks membership in a list?','IN','WITH','LIST','ANYOF','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Which condition checks for NULL?','= NULL','IS NULL','NULL =','CHECK NULL','B','The correct answer is B. This is a fundamental Database concept.','medium'),
('5','Which keyword combines query results and removes duplicates?','JOIN','UNION','MERGE','COMBINE','B','The correct answer is B. This is a fundamental Database concept.','medium'),
('5','Which JOIN returns matching rows from both tables?','INNER JOIN','LEFT JOIN','RIGHT JOIN','FULL ONLY','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Which JOIN keeps all left-table rows?','INNER JOIN','LEFT JOIN','RIGHT JOIN','LEFT ONLY','B','The correct answer is B. This is a fundamental Database concept.','medium'),
('5','Which JOIN keeps all right-table rows?','RIGHT JOIN','LEFT JOIN','INNER JOIN','RIGHT ONLY','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Why is normalization used?','To reduce redundancy and improve integrity','To add duplicate data','To color queries','To encrypt passwords','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','What is an index mainly used for?','Improving data retrieval performance','Storing images only','Replacing tables','Encrypting rows','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','What is a transaction?','A logical unit of database work','A table column','A database password','A query comment','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Which command permanently saves a transaction?','SAVE','COMMIT','APPLY','STORE','B','The correct answer is B. This is a fundamental Database concept.','medium'),
('5','Which command undoes uncommitted changes?','UNDO','ROLLBACK','REVERSE','CANCEL SQL','B','The correct answer is B. This is a fundamental Database concept.','medium'),
('5','Which command starts a transaction?','START TRANSACTION','BEGIN QUERY','OPEN TRANSACTION','NEW TRANSACTION','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','What does ACID A mean?','Atomicity','Accuracy','Availability','Access','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','What does ACID C mean?','Consistency','Correctness','Connection','Control','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','What does ACID I mean?','Isolation','Integrity','Indexing','Input','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','What does ACID D mean?','Durability','Data','Dependency','Distribution','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','What is a view?','A virtual table based on a query','A physical hard drive','A backup file','A database user','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Which statement creates a view?','CREATE VIEW','MAKE VIEW','NEW VIEW','VIEW CREATE','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Which command grants privileges?','GRANT','ALLOW','PERMIT','ACCESS','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('5','Which command removes privileges?','REMOVE','REVOKE','DENYALL','UNGRANT','B','The correct answer is B. This is a fundamental Database concept.','medium'),
('5','What does RDBMS mean?','Relational Database Management System','Remote Database Backup Management System','Rapid Data Business Management Service','Relational Data Backup Machine System','A','The correct answer is A. This is a fundamental Database concept.','medium'),
('6','What is the capital of France?','Berlin','Madrid','Paris','Rome','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','What is the largest planet?','Earth','Jupiter','Saturn','Neptune','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which planet is called the Red Planet?','Venus','Mars','Mercury','Jupiter','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','How many continents are commonly recognized?','5','6','7','8','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','What is the largest ocean?','Atlantic Ocean','Indian Ocean','Pacific Ocean','Arctic Ocean','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','Which gas do humans need for respiration?','Carbon dioxide','Oxygen','Nitrogen','Hydrogen','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','What is H2O commonly called?','Oxygen','Hydrogen','Water','Salt','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','How many days are in a leap year?','365','366','364','360','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','What is the smallest prime number?','0','1','2','3','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','What is 12 × 12?','124','132','144','154','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','Which organ pumps blood?','Lungs','Brain','Heart','Liver','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','Which organs are mainly responsible for breathing?','Heart','Lungs','Kidneys','Stomach','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Approximately how many bones are in an adult human body?','106','206','306','406','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which vitamin is commonly produced through sunlight exposure?','Vitamin A','Vitamin B12','Vitamin C','Vitamin D','D','The correct answer is D. This is a fundamental General Knowledge concept.','easy'),
('6','Which metal is liquid at room temperature?','Iron','Mercury','Copper','Aluminum','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','What is the chemical symbol for gold?','Ag','Au','Gd','Go','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','What is the chemical symbol for oxygen?','O','Ox','Og','C','A','The correct answer is A. This is a fundamental General Knowledge concept.','easy'),
('6','Which force keeps planets in orbit?','Magnetism','Gravity','Friction','Pressure','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','How many degrees are in a right angle?','45','90','180','360','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','How many sides does a hexagon have?','5','6','7','8','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which language has the largest number of native speakers?','English','Spanish','Mandarin Chinese','French','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','Which country is famous for the Great Wall?','Japan','China','India','Korea','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which city is called the Big Apple?','London','New York City','Los Angeles','Chicago','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which country is shaped like a boot?','Italy','Greece','Portugal','Chile','A','The correct answer is A. This is a fundamental General Knowledge concept.','easy'),
('6','Which is the largest continent by area?','Africa','Asia','Europe','North America','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which is the largest hot desert?','Gobi','Sahara','Kalahari','Atacama','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which is the fastest land animal?','Lion','Cheetah','Horse','Leopard','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which is the largest mammal?','Elephant','Blue whale','Giraffe','Hippopotamus','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','What do bees primarily collect from flowers?','Leaves','Nectar','Soil','Bark','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which bird is known for mimicking human speech?','Eagle','Parrot','Penguin','Ostrich','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','What is water''s freezing point in Celsius?','0°C','10°C','32°C','100°C','A','The correct answer is A. This is a fundamental General Knowledge concept.','easy'),
('6','What is water''s boiling point at standard pressure?','50°C','75°C','100°C','150°C','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','How many minutes are in one hour?','30','45','60','90','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','How many seconds are in one minute?','30','60','90','100','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which instrument has black and white keys?','Guitar','Piano','Violin','Flute','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which sport uses a racket and shuttlecock?','Tennis','Badminton','Football','Basketball','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','How many players are on a standard football team on the field?','9','10','11','12','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','Which sport is associated with Wimbledon?','Cricket','Tennis','Rugby','Golf','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','How many rings are on the Olympic symbol?','4','5','6','7','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which planet is closest to the Sun?','Venus','Mercury','Earth','Mars','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','What natural satellite orbits Earth?','Mars','Moon','Sun','Venus','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','How do plants make food using light?','Respiration','Photosynthesis','Digestion','Fermentation','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which plant part usually absorbs water from soil?','Flower','Roots','Fruit','Leaf','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','What is the largest internal organ?','Heart','Liver','Lung','Kidney','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which blood type is commonly called a universal donor for red blood cells?','AB+','O-','A+','B-','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which device measures temperature?','Barometer','Thermometer','Hygrometer','Compass','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy'),
('6','Which instrument measures atmospheric pressure?','Barometer','Thermometer','Speedometer','Altimeter','A','The correct answer is A. This is a fundamental General Knowledge concept.','easy'),
('6','What is Japan''s currency?','Won','Yuan','Yen','Ringgit','C','The correct answer is C. This is a fundamental General Knowledge concept.','easy'),
('6','Which country is home to the pyramids of Giza?','Mexico','Egypt','Peru','Jordan','B','The correct answer is B. This is a fundamental General Knowledge concept.','easy');

-- Verify the imported question counts:
SELECT category_id, COUNT(*) AS total_questions
FROM questions
GROUP BY category_id
ORDER BY category_id;

SELECT * FROM quiz_results;